server:
  port: 8081
spring:
  profiles:
    active: prod
---
server:
     port: 8085
spring:
  profiles: dev
person:
  last-name: aaa
---
server:
  port: 8086
spring:
  profiles: prod
person:
  last-name: louhu